# Generated by Django 2.2.2 on 2019-07-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('GaurdainsName', models.CharField(max_length=30)),
                ('Occupation', models.CharField(default='Agricultural', max_length=30)),
                ('MailingAddress', models.CharField(default='Kathmandu', max_length=30)),
                ('Gender', models.CharField(default='Male', max_length=20)),
                ('PhoneNumber', models.CharField(default='None', max_length=10)),
                ('Services', models.CharField(default='None', max_length=30)),
                ('LastteachingInstitution', models.CharField(default='None', max_length=400)),
                ('runningteachingInstitution', models.CharField(default='None', max_length=1000)),
                ('PercentageinlastGrade', models.CharField(default='0', max_length=2)),
                ('HigherGrade', models.CharField(default='one', max_length=2)),
            ],
        ),
    ]
