# Generated by Django 2.2.2 on 2019-07-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20190730_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_detail',
            name='gmailid',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
