# Generated by Django 2.2.2 on 2019-08-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_detail_gmailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_detail',
            name='image',
            field=models.ImageField(blank=True, default='/images/avatar.jpg', null=True, upload_to='images/profile/'),
        ),
    ]
