# Generated by Django 2.2.2 on 2019-10-27 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacher_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_detail',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
