# Generated by Django 2.2.2 on 2019-10-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20191027_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher_detail',
            name='Services',
        ),
        migrations.AddField(
            model_name='teacher_detail',
            name='Services',
            field=models.ManyToManyField(to='teacher.Services'),
        ),
    ]
