# Generated by Django 2.2.2 on 2019-11-04 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='std_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('date', models.DateField(blank=True)),
                ('GaurdainsName', models.CharField(max_length=30)),
                ('emailid', models.CharField(default='none', max_length=40)),
                ('image', models.ImageField(blank=True, default='/images/avatar.jpg', null=True, upload_to='images/profile/')),
                ('Occupation', models.CharField(default='Agricultural', max_length=30)),
                ('MailingAddress', models.CharField(default='Kathmandu', max_length=30)),
                ('currentgrade', models.CharField(choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten')], default='Two', max_length=30)),
                ('Gender', models.CharField(default='Male', max_length=20)),
                ('PhoneNumber', models.CharField(default='None', max_length=10)),
                ('Hobbies', models.CharField(default='none', max_length=20)),
                ('dues', models.IntegerField(default='0')),
                ('payment', models.IntegerField(default='0')),
                ('Transportation', models.BooleanField(default=False)),
                ('Hostel', models.BooleanField(default=False)),
                ('Computer', models.BooleanField(default=False)),
                ('LastInstitution', models.CharField(default='None', max_length=40)),
                ('Percentage', models.CharField(default='0', max_length=2)),
                ('Grade', models.CharField(default='one', max_length=2)),
                ('Players', models.CharField(default='None', max_length=30)),
            ],
            options={
                'db_table': 'std_detail',
            },
        ),
        migrations.CreateModel(
            name='studentfee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, choices=[('Select Year', 'Select Year'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2023', '2024')], max_length=1000, null=True)),
                ('classnam', models.CharField(blank=True, choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten')], max_length=1000, null=True)),
                ('monthlyfee', models.IntegerField()),
                ('admissionfee', models.IntegerField()),
                ('transfee', models.IntegerField()),
                ('compfee', models.IntegerField()),
                ('hostelfee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='feeadd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField()),
                ('dues', models.IntegerField(default=0)),
                ('advance', models.IntegerField(default=0)),
                ('paydate', models.DateField(auto_now_add=True)),
                ('studentname', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='students.std_detail')),
            ],
        ),
    ]
