# Generated by Django 2.2.2 on 2019-11-04 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20191104_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeadd',
            name='paydate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='feeadd',
            name='studentname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.std_detail'),
        ),
    ]
