# Generated by Django 2.2.2 on 2019-08-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stdfee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('classname', models.CharField(max_length=1000)),
                ('monthlyfee', models.IntegerField()),
                ('admissionfee', models.IntegerField()),
                ('transfee', models.IntegerField()),
                ('compfee', models.IntegerField()),
                ('hostelfee', models.IntegerField()),
            ],
        ),
    ]
