# Generated by Django 2.2.2 on 2019-10-29 15:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailaddress', '0002_auto_20190802_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailaddress',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
