# Generated by Django 2.2.2 on 2019-10-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailaddress', '0004_mailaddress_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailaddress',
            name='created_at',
        ),
    ]
