# Generated by Django 2.2.2 on 2019-06-21 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cebsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
                ('categories', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('save', models.IntegerField(max_length=1)),
                ('discard', models.IntegerField(max_length=1)),
                ('send', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
