# Generated by Django 2.2.2 on 2019-06-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cebsapp', '0002_auto_20190621_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('date', models.DateField(auto_now=True)),
                ('categories', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=1)),
            ],
        ),
    ]
