
# Generated by Django 2.2.3 on 2019-07-09 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cebsapp', '0003_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
