# Generated by Django 2.2.2 on 2019-07-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cebsapp', '0003_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
