# Generated by Django 2.2.2 on 2019-07-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190702_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_detail',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='student_detail',
            name='Grade',
        ),
        migrations.RemoveField(
            model_name='student_detail',
            name='Hobbies',
        ),
        migrations.RemoveField(
            model_name='student_detail',
            name='Hostel',
        ),
        migrations.RemoveField(
            model_name='student_detail',
            name='LastInstitution',
        ),
        migrations.RemoveField(
            model_name='student_detail',
            name='MailingAddress',
        ),
        migrations.RemoveField(
            model_name='student_detail',
            name='Occupation',
        ),
        migrations.RemoveField(
            model_name='student_detail',
            name='Percentage',
        ),
        migrations.RemoveField(
            model_name='student_detail',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='student_detail',
            name='Players',
        ),
        migrations.RemoveField(
            model_name='student_detail',
            name='Transportaion',
        ),
    ]
