# Generated by Django 2.2.2 on 2019-07-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190711_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='Gender',
            field=models.CharField(default='Male', max_length=20),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='Grade',
            field=models.CharField(default='one', max_length=2),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='Hobbies',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='LastInstitution',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='MailingAddress',
            field=models.CharField(default='Kathmandu', max_length=30),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='Occupation',
            field=models.CharField(default='Agricultural', max_length=30),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='Percentage',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='PhoneNumber',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='Players',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='Services',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
