# Generated by Django 2.2.2 on 2019-08-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_detail_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='image',
            field=models.ImageField(default='/media/images/avatar.jpg', upload_to='images/'),
        ),
    ]
