# Generated by Django 2.2.2 on 2019-08-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='image',
            field=models.ImageField(default='/images/avatar.jpg', upload_to='images/'),
        ),
    ]
