# Generated by Django 2.2.2 on 2019-08-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20190809_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
