# Generated by Django 2.2.2 on 2019-08-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_student_detail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_detail',
            name='image',
        ),
    ]
