# Generated by Django 2.2.2 on 2019-08-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_remove_student_detail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='image',
            field=models.ImageField(default='images/avatar.jpg', upload_to='images/'),
        ),
    ]
