# Generated by Django 2.2.2 on 2019-08-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20190809_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_detail',
            name='image',
        ),
    ]
