# Generated by Django 2.2.2 on 2019-08-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_student_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='image',
            field=models.ImageField(blank=True, default='images/avatar.jpg', null=True, upload_to='images/'),
        ),
    ]
