# Generated by Django 2.2.2 on 2019-08-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_auto_20190811_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='image',
            field=models.ImageField(blank=True, default='images/avatar.jpg', null=True, upload_to='images/profile/'),
        ),
    ]
