# Generated by Django 2.2.2 on 2019-08-13 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_auto_20190811_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='classfee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=2)),
                ('fees', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.IntegerField()),
                ('advance', models.IntegerField()),
                ('monthlyfees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.classfee')),
                ('studentname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_detail')),
            ],
        ),
    ]
