# Generated by Django 2.2.2 on 2019-08-13 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_auto_20190813_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='studentname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student_detail'),
        ),
    ]
