# Generated by Django 2.2.2 on 2019-08-13 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_auto_20190813_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfee',
            name='Computercharge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classfee',
            name='transportationcharge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fee',
            name='studentname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_detail'),
        ),
    ]
