# Generated by Django 2.2.2 on 2019-08-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_auto_20190814_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
