# Generated by Django 2.2.2 on 2019-08-15 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_auto_20190814_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='monthlyfees',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='studentname',
        ),
        migrations.DeleteModel(
            name='classfee',
        ),
        migrations.DeleteModel(
            name='fee',
        ),
    ]
