# Generated by Django 2.2.2 on 2019-09-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_auto_20190815_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentfee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('classname', models.CharField(max_length=1000)),
                ('monthlyfee', models.IntegerField()),
                ('admissionfee', models.IntegerField()),
                ('transfee', models.IntegerField()),
                ('compfee', models.IntegerField()),
                ('hostelfee', models.IntegerField()),
            ],
        ),
    ]
