# Generated by Django 2.2.2 on 2019-09-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_studentfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='currentgrade',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
