# Generated by Django 2.2.2 on 2019-10-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryig', '0004_auto_20191023_2145'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
