# Generated by Django 2.2.2 on 2019-10-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryig', '0005_auto_20191024_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Grade',
            field=models.CharField(default='o', max_length=2),
        ),
    ]
