# Generated by Django 2.2.2 on 2019-10-25 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tryig', '0006_auto_20191024_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
